clasicas:
- pizza
- sushi
- milanesa
- hamburguesa
- empanadas
- pollo
- picada
- parrilla
- pastas
- ensalada
- sandwich
etnicas:
- comida china
- comida armenia
- comida peruana
- comida india
- comida mexicana
